apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: react
  replicas: 5  #run 2 pods 
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name:  react
        image: simadock/react-docker-test-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080