apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: 
spec:
  containers:
  - name: my-pod
    image: vish/stress
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: "0.5"
        memory: 500Mi
    args:
    - -cpus
    - "2"